#!/usr/bin/env bash
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

if [ $# -eq 3 ]
then
    max_tests=10
else
    max_tests=$4
fi

echo Compiling $3.cc......
g++ -std=c++17 -O2 -Wall -DLOCAL $3.cc -o $3
echo Compiling $2.cc......
g++ -std=c++17 -O2 -Wall -DLOCAL $2.cc -o $2
echo Compiling $1.cc......
g++ -std=c++17 -O2 -Wall -DLOCAL $1.cc -o $1

for ((test_num=1;test_num<=$max_tests;test_num++))
do
    ./$3 > Input
    ./$2 < Input > Expected
    ./$1 < Input > Output

    if !(diff -B -Z Expected Output > diff_buffer)
    then
        echo -e "${RED}Wrong answer on test" $test_num"${NC}"  
        echo -e "${BLUE}Input:${NC}"
        cat Input
        echo -e "${BLUE}Output:${NC}"
        cat Output
        echo -e "${BLUE}Expected:${NC}"
        cat Expected
        rm $1 $2 $3 diff_buffer
        exit
    fi
done

echo -e ${GREEN}$max_tests "tests" "Passed"${NC}
rm $1 $2 $3 diff_buffer
